blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/magnon-compute/.github/blob/main/SECURITY.md
    about: Report security vulnerabilities to security@magnoncompute.com
